### ISSUE TITLE
PropHunt T0

### ISSUE THREAD

**Issue by Leirof** [Creative-Olympics/CO2-Datapacks#4]
![Image](https://user-images.githubusercontent.com/12165342/266817212-c96b3ce3-ae1e-45a0-884f-7fd999474046.png)

# Concept

Create a prophunt minigame based on "Mischief & Magic", a prophunt variation made by Blizzard during the season 5 of Overwatch 2.

# Tasks

- [x] Simple prop position sync
- [x] Complexe prop position sync
- [x] Lock (alignment to the world grid) system
- [x] Flashbang system (stun hunters)
- [x] Prop switching system
- [x] Prop variation cycle
- [x] Climbing system
- [x] Taunt system (indication of the prop position)
- [x] Hunter dash
- [x] Ping system
- [x] Hunter special ability
- [x] Kill system & spectator mode
- [x] Game management system
--- Playable ---
- [x] Timer on sidebar
- [ ] Area limits
- [ ] Build adaptation
- [ ] Fake props variation

**Comment by Leirof** [comment]
# Prop display

![Image](https://github.com/Creative-Olympics/CO2-Public-Map/assets/12165342/fc453ae4-ff1e-4d28-a025-7195365f9bf7)


Video: https://cdn.discordapp.com/attachments/1036923112626847775/1139206237205045278/Untitled_video_1.mp4

**Comment by Leirof** [comment]
# Prop switch ✅ 



![Image](https://github.com/Creative-Olympics/CO2-Public-Map/assets/12165342/f7969265-6a7a-4b00-8fe8-7353ce96124a)

**Comment by Leirof** [comment]
# Complexe prop display ✅ 



![Image](https://github.com/Creative-Olympics/CO2-Public-Map/assets/12165342/e32bfcef-5b32-45c4-b4b0-eab93d520007)

**Comment by Leirof** [comment]
# Victory screen



![Image](https://github.com/Creative-Olympics/CO2-Public-Map/assets/12165342/a42985e9-d0cb-41df-a954-51671111ce09)

Video: https://cdn.discordapp.com/attachments/1036923112626847775/1153966012102873198/Video_sans_titre_8.mp4
