### ISSUE TITLE
One In The Chamber T0

### ISSUE THREAD

**Issue by Leirof** [Creative-Olympics/CO2-Datapacks#6]
# Description

1 bow that one-shot, 1 arrow, 1 shitty wood sword, free for all. Kill someone give you an additional arrow (if you use yours). The first player having 10 kills win the game

# Tasks
- [x] Kill mechanic with animation
- [x] Win condition and animation
- [x] Game management system
- [x] Zone restriction (prevent players to exit or non-player to enter in the fight area)
- [ ] Build adaptation
